baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Eric Berg - technical writing portfolio'
theme = 'book'

[params]
  BookSearch = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

